---
title: "P8105_hw2_yx2638"
author: "Yifei Xu"
date: "2022-09-28"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,  message=FALSE}
library(tidyverse)
```


# Problem 1

```{r}
# Read and clean the data
transit_df = read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
        janitor::clean_names() %>%
        select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, 
               entrance_type,  ada) %>%
        mutate(entry = recode(entry, "YES" = "TRUE", "NO" = "FALSE"),
               entry = as.logical(entry))


# names of important variables
variable_name = names(transit_df)

# size of the dataset 
row = nrow(transit_df)
col = ncol(transit_df)
```

```{r}
# Count the number of distinct stations
station_num = nrow(distinct(transit_df, line, station_name))

# Count the number of stations that are ADA compliant
ada_station_num = transit_df %>%
        filter(ada == "TRUE") %>%
        distinct(line, station_name) %>%
        nrow()

# Calculte the proportion of station entrances / exits without vending allow entrance?????
no_vending_extrance_num = transit_df %>%
        filter(entry == "TRUE", vending == "NO") %>%
        distinct(line, station_name) %>%
        nrow()

entrance_num = transit_df %>%
        filter(entry == "TRUE") %>%
        distinct(line, station_name) %>%
        nrow()

no_vending_extrance_prop = scales::percent(no_vending_extrance_num / entrance_num, 0.01)
```

```{r}
# Reformat data so that route number and route name are distinct variables
transit_df_tidy = transit_df %>%
        mutate(
                route8 = as.character(route8),
                route9 = as.character(route9),
                route10 = as.character(route10),
                route11 = as.character(route11)
               ) %>%
        pivot_longer(
                route1:route11,
                names_to = "route_number",
                values_to = "route_name"
                )

# Count the number of distinct stations serve the A train
station_a_num = transit_df_tidy %>%
        filter(route_name == "A") %>%
        distinct(line, station_name) %>%
        nrow()

# Count the number of ADA compliant of the stations that serve the A train
station_a_ada_num = transit_df_tidy %>%
        filter(route_name == "A", ada == "TRUE") %>%
        distinct(line, station_name) %>%
        nrow()
```


# Problem 2

```{r}
# Read and clean the Mr. Trash Wheel sheet
mr_trash = readxl::read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
                                 sheet = "Mr. Trash Wheel", range = "A2:N535") #???homes_power

mr_trash_tidy = mr_trash %>%
        janitor::clean_names() %>%
        drop_na() %>% #??grand total
        mutate(sports_balls = as.integer(round(sports_balls, digits = 0)))
```

```{r}
# Read and clean the Professor Trash Wheel sheet
prof_trash = readxl::read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
                                 sheet = "Professor Trash Wheel", range = "A2:N117") #???homes_power

prof_trash_tidy = mr_trash %>%
        janitor::clean_names() %>%
        drop_na() %>% #??grand total
        mutate(sports_balls = as.integer(round(sports_balls, digits = 0)))

```

```{r}
# Add a new variable in these two datasets
mr_trash_tidy_comb = mr_trash_tidy %>%
        mutate(name = "Mr. Trash Wheel")

prof_trash_tidy_comb = prof_trash_tidy %>%
        mutate(name = "Professor Trash Wheel")

# Combine these two datasets
mr_prof_trash = bind_rows(mr_trash_tidy_comb, prof_trash_tidy_comb) %>%
        select(name, everything())

```

```{r}
# Count the number of observations in the resulting dataset
mr_prof_nrow = nrow(mr_prof_trash)

# Give examples of key variables
mr_prof_var = names(mr_prof_trash)

# Calculate the total weight of trash collected by Professor Trash Wheel
prof_total_weight = mr_prof_trash %>%
        filter(name == "Professor Trash Wheel") %>%
        sum()

# Count the total number of sports balls collected by Mr. Trash Wheel in 2020
mr_total_balls = mr_prof_trash %>%
        filter(name == "Mr. Trash Wheel", year == "2020") %>%
        pull(sports_balls) %>%
        sum()
```

# Problem 3

```{r}
# Read and clean the data in pols-month.csv
pols = read_csv("data/pols-month.csv")

pols_tidy = pols_mon %>%
        janitor::clean_names() %>%
        separate(mon, into = c("year", "month", "day")) %>%
        mutate(
                month = month.name[as.numeric(month)],
                year = as.numeric(year),
                president = case_when(prez_dem == 1 ~ "dem",
                               prez_gop == 1 ~ "gop",
                               prez_gop == 2 ~ "gop") 
                )%>%
    select(-day, -prez_dem, -prez_gop)
```

```{r}
# Read and clean the data in snp.csv
snp = read_csv("data/snp.csv")

snp_tidy = snp %>%
        janitor::clean_names() %>%
        separate(date, into = c("month", "day", "year"), sep ="/") %>%
        mutate(
                month = month.name[as.numeric(month)],
                year = as.numeric(year),
                year = ifelse(year < 23, year+2000, year+1900)
                ) %>%
        arrange(year, month) %>%
        select(year, month, close)
```

```{r}
# Read and clean the data in unemployment.csv
unemployment = read_csv("data/unemployment.csv")

unemployment_tidy = unemployment %>%
        pivot_longer(
                Jan:Dec,
                names_to = "month",
                values_to = "unemployment_percent"
        ) %>%
        janitor::clean_names() %>% 
        mutate(
                month = match(month, month.abb),
                month = month.name[month]
                ) %>%
        arrange(year, month) 

```

```{r}
# Join Join the datasets by merging snp into pols
pols_snp = left_join(pols_tidy, snp_tidy, by = c("year","month"))

# Join the datasets by merging unemployment into the result
pols_snp_employment = left_join(pols_snp, unemployment_tidy, by = c("year","month"))
```








